[tool.bumpversion]
current_version = "0.9.1"

# Parse pattern that understands both regular and preview versions  
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:-(?P<stage>preview)\\.(?P<preview>\\d+))?"

# Preview serialization - always includes preview suffix
serialize = [
    "{major}.{minor}.{patch}-{stage}.{preview}"  # Preview versions: 0.9.1-preview.1
]

commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "Preview {new_version}"
message = "Bump version: {current_version} → {new_version}"

# PREVIEW CONFIG: Update package.json AND sync release config

[[tool.bumpversion.files]]
filename = "package.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

# Keep release config in sync
[[tool.bumpversion.files]]
filename = ".bumpversion.toml"
search = 'current_version = "{current_version}"'
replace = 'current_version = "{new_version}"'

# Stage part: always "preview" for this config
[tool.bumpversion.parts.stage]
values = ["preview"]

# Preview part: for incrementing preview numbers
[tool.bumpversion.parts.preview]
first_value = "1"
