[tool.bumpversion]
current_version = "0.9.2-preview.1"

# Parse pattern that understands both regular and preview versions
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:-(?P<stage>preview)\\.(?P<preview>\\d+))?"

# Release serialization - always removes preview suffix
serialize = [
    "{major}.{minor}.{patch}"  # Final releases: 0.9.1
]

commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "Release {new_version}"
message = "Bump version: {current_version} → {new_version}"

# RELEASE CONFIG: Update package.json, manifest.json, AND sync preview config

[[tool.bumpversion.files]]
filename = "package.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

[[tool.bumpversion.files]]
filename = "manifest.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

# Keep preview config in sync
[[tool.bumpversion.files]]
filename = ".bumpversion-preview.toml"
search = 'current_version = "{current_version}"'
replace = 'current_version = "{new_version}"'

# Stage part: preview -> final (final is hidden in serialization)
[tool.bumpversion.parts.stage]
values = ["preview", "final"]
optional_value = "final"

# Preview part: for incrementing preview numbers
[tool.bumpversion.parts.preview]
first_value = "1"
